# Generated by Django 2.2.24 on 2022-11-09 11:37

from django.db import migrations

import phonenumbers


def get_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for building in Flat.objects.all().iterator():
        building.owners_phonenumber
        number_parse = phonenumbers.parse(building.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(number_parse):
            building.owner_pure_phone = phonenumbers.format_number(
                number_parse,
                phonenumbers.PhoneNumberFormat.E164
            )
            building.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20221109_1831'),
    ]

    operations = [
        migrations.RunPython(get_owner_pure_phone)
    ]
