# Generated by Django 2.2.24 on 2022-11-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20221117_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner_deprecated',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО владельца'),
        ),
    ]
