# Generated by Django 2.2.24 on 2022-11-19 07:18

from django.db import migrations


def copy_fields(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all().iterator():
        owner, created = Owner.objects.get_or_create(
            owner=flat.owner_deprecated,
            owner_pure_phone=flat.owner_pure_phone,
            owners_phonenumber=flat.owners_phonenumber
        )
        owner.flats.add(flat)
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20221118_1845'),
    ]

    operations = [
        migrations.RunPython(copy_fields)
    ]
