# Generated by Django 2.2.24 on 2022-11-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20221123_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owners_phonenumber',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Номер владельца'),
        ),
    ]
